[phases.setup]
nixPkgs = ["ffmpeg", "python311", "gunicorn"]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:5000 backend.app:app"
