[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.start]
cmds = ["python3 -m uvicorn backend.app:app --host 0.0.0.0 --port 8080"]
